export const COLORS = [
  // Neutrals
  "Black",
  "White",
  "Snow",
  "WhiteSmoke",
  "Ivory",
  "Beige",
  "Linen",
  "OldLace",
  "Wheat",
  "Cornsilk",
  "FloralWhite",
  "GhostWhite",
  "Gainsboro",
  "Silver",
  "Gray",
  "Grey",
  "DarkGray",
  "DarkGrey",
  "LightGray",
  "LightGrey",
  "DimGray",
  "DimGrey",
  "SlateGray",
  "SlateGrey",
  "DarkSlateGray",
  "DarkSlateGrey",

  // Reds
  "Red",
  "DarkRed",
  "Crimson",
  "FireBrick",
  "IndianRed",
  "Tomato",
  "Coral",
  "Salmon",
  "DarkSalmon",
  "LightCoral",
  "Maroon",
  "Burgundy",

  // Pinks
  "Pink",
  "HotPink",
  "DeepPink",
  "LightPink",
  "MistyRose",
  "LavenderBlush",
  "PaleVioletRed",
  "MediumVioletRed",

  // Oranges
  "Orange",
  "DarkOrange",
  "OrangeRed",
  "PeachPuff",
  "PapayaWhip",
  "Moccasin",
  "Bisque",

  // Yellows / Golds
  "Yellow",
  "LightYellow",
  "Gold",
  "GoldenRod",
  "DarkGoldenRod",
  "Khaki",
  "DarkKhaki",
  "LemonChiffon",

  // Browns / Earth
  "Brown",
  "SaddleBrown",
  "Sienna",
  "Peru",
  "Chocolate",
  "Tan",
  "BurlyWood",
  "SandyBrown",
  "RosyBrown",

  // Greens
  "Green",
  "DarkGreen",
  "LightGreen",
  "PaleGreen",
  "SeaGreen",
  "MediumSeaGreen",
  "DarkSeaGreen",
  "SpringGreen",
  "MediumSpringGreen",
  "Lime",
  "LimeGreen",
  "LawnGreen",
  "GreenYellow",
  "Chartreuse",
  "Olive",
  "OliveDrab",
  "DarkOliveGreen",
  "ForestGreen",
  "HoneyDew",

  // Cyans / Teals / Turquoise
  "Cyan",
  "Aqua",
  "Aquamarine",
  "Turquoise",
  "PaleTurquoise",
  "DarkTurquoise",
  "MediumTurquoise",
  "Teal",
  "DarkCyan",
  "LightCyan",

  // Blues
  "Blue",
  "DarkBlue",
  "Navy",
  "MidnightBlue",
  "RoyalBlue",
  "DodgerBlue",
  "DeepSkyBlue",
  "SkyBlue",
  "LightSkyBlue",
  "LightBlue",
  "PowderBlue",
  "CornflowerBlue",
  "SteelBlue",
  "LightSteelBlue",
  "CadetBlue",
  "SlateBlue",
  "LightSlateGray",
  "LightSlateGrey",
  "DarkSlateBlue",
  "MediumBlue",
  "MediumSlateBlue",
  "MediumAquaMarine",

  // Purples / Violets
  "Purple",
  "RebeccaPurple",
  "Indigo",
  "Violet",
  "DarkViolet",
  "BlueViolet",
  "DarkOrchid",
  "Orchid",
  "MediumOrchid",
  "MediumPurple",
  "Magenta",
  "Fuchsia",
  "DarkMagenta",
  "Plum",
  "Thistle",

  // Whites / Very light tints
  "AliceBlue",
  "Azure",
  "MintCream",
  "SeaShell",
  "BlanchedAlmond",
  "NavajoWhite",
  "PaleGoldenRod",
  "LightGoldenRodYellow",
  "LightSalmon",
];
export const SIZES = ["XS", "S", "M", "L", "XL", "XXL"];
export const PERCENTAGE = [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.4, 0.5];
